#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ppft
Version  : 1.6.6.4
Release  : 3
URL      : https://github.com/uqfoundation/ppft/releases/download/ppft-1.6.6.4/ppft-1.6.6.4.tar.gz
Source0  : https://github.com/uqfoundation/ppft/releases/download/ppft-1.6.6.4/ppft-1.6.6.4.tar.gz
Summary  : distributed and parallel python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: ppft-bin = %{version}-%{release}
Requires: ppft-license = %{version}-%{release}
Requires: ppft-python = %{version}-%{release}
Requires: ppft-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(six)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
### VERSION 1.6.6.3 ###
# see MODS*.diff for full patch (against 1.6.6)
# made these functional changes
- ...TBD...

%package bin
Summary: bin components for the ppft package.
Group: Binaries
Requires: ppft-license = %{version}-%{release}

%description bin
bin components for the ppft package.


%package license
Summary: license components for the ppft package.
Group: Default

%description license
license components for the ppft package.


%package python
Summary: python components for the ppft package.
Group: Default
Requires: ppft-python3 = %{version}-%{release}

%description python
python components for the ppft package.


%package python3
Summary: python3 components for the ppft package.
Group: Default
Requires: python3-core
Provides: pypi(ppft)
Requires: pypi(six)

%description python3
python3 components for the ppft package.


%prep
%setup -q -n ppft-1.6.6.4
cd %{_builddir}/ppft-1.6.6.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644189858
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ppft
cp %{_builddir}/ppft-1.6.6.4/COPYING %{buildroot}/usr/share/package-licenses/ppft/7dd3b63ab14ec21f8db6b624104d1677a7cffaed
cp %{_builddir}/ppft-1.6.6.4/LICENSE %{buildroot}/usr/share/package-licenses/ppft/ecf0a987e6520b800ca6ce21de467cb3f255cf4d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ppserver

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ppft/7dd3b63ab14ec21f8db6b624104d1677a7cffaed
/usr/share/package-licenses/ppft/ecf0a987e6520b800ca6ce21de467cb3f255cf4d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
